<template>
  <div id="sampleInfo" >
    <!-- 样品测试测试信息 -->
    <!-- 样品信息 -->
    <el-table
        v-show="this.testType=='样品测试'"
        :header-cell-style="{
            backgroundColor:'#06426e',
            color:'#fff',
            'text-align':'center'
        }"
        :cell-style="{
            backgroundColor:'#06426e',
            color:'#fff',
            textAlign:'center'
        }"
            :border="isBorder"
            :data="tableData_sample"
            style="width: 100%;">
            <el-table-column
            prop="testPurpose"
            label="测试目的"
            >
            </el-table-column>
            <el-table-column
            prop="sampleName"
            label="样品名称"
            >
            </el-table-column>
            <el-table-column
            prop="totalQuantity"
            label="样品总数量">
            </el-table-column>
            <el-table-column
            prop="batchNo"
            label="灭菌批号">
            </el-table-column>
            <el-table-column
            prop="disposal"
            label="样品处置">
            </el-table-column>
            <el-table-column
            prop="storageCondition"
            label="样品存储条件">
            </el-table-column>
            <el-table-column
            prop="status"
            label="状态">
            </el-table-column>
        </el-table>
        <!-- 测试项目信息 -->
        <el-table
        v-show="this.testType=='样品测试'"
        :header-cell-style="{
            backgroundColor:'#06426e',
            color:'#fff',
            'text-align':'center'
        }"
        :cell-style="{
            backgroundColor:'#06426e',
            color:'#fff',
            textAlign:'center'
        }"
            :border="isBorder"
            :data="tableData_sample_testProject"
            style="width: 100%;">
            <el-table-column
            prop="model"
            label="规格"
            >
            </el-table-column>
            <el-table-column
            prop="lotNo"
            label="批号"
            >
            </el-table-column>
            <el-table-column
            prop="quantity"
            label="数量">
            </el-table-column>
            <el-table-column
            prop="testItem"
            label="测试项目">
            </el-table-column>
            <el-table-column
            prop="wiNo"
            label="测试方法号">
            </el-table-column>
            <el-table-column
            prop="limitValue"
            label="接收限值">
            </el-table-column>
            <el-table-column
            prop="status"
            label="状态">
            </el-table-column>
        </el-table>

        <!-- 纯化水测试和洁净室环境测试测试信息 -->
        <el-table
        v-show="this.testType=='纯化水测试'||this.testType=='洁净室环境测试'"
        :header-cell-style="{
            backgroundColor:'#06426e',
            color:'#fff',
            'text-align':'center'
        }"
        :cell-style="{
            backgroundColor:'#06426e',
            color:'#fff',
            textAlign:'center'
        }"
            :border="isBorder"
            :data="tableData_purifiedWater_cleanroom"
            style="width: 100%;">
            <el-table-column
            prop="purifiedWaterNo"
            label="纯化水编号"
            v-if="this.testType=='纯化水测试'"
            >
            </el-table-column>
            <el-table-column
            prop="cleanroom"
            label="洁净室名称"
            v-if="this.testType=='洁净室环境测试'"
            >
            </el-table-column>
            <el-table-column
            prop="testProject"
            label="测试项目"
            >
            </el-table-column>
            <el-table-column
            prop="WINo"
            label="WINo">
            </el-table-column>
            <el-table-column
            prop="status"
            label="状态">
            </el-table-column>
        </el-table>
  </div>
</template>

<script>
export default {
    name:'testInfo',
    data(){
        return{
            isBorder:true,
            tableData_sample:[
                {
                    testPurpose:'',
                    sampleName:'',
                    totalQuantity:0,
                    batchNo:'',
                    disposal:'',
                    storageCondition:'',
                    status:'',
                }
            ],
            tableData_purifiedWater_cleanroom:[
                {
                    purifiedWaterNo:'159',
                    testProject:'159',
                    WINo:'159',
                    status:'159',
                }
            ],
            tableData_sample_testProject:[
                {
                    model:"753",
                    lotNo:"156",
                    quantity:2,
                    testItem:"/",
                    wiNo:"/",
                    limitValue:"/",
                }
            ],
            testType:'',
            
        }
    },
    created(){
        this.init()
    },
    methods:{
        init(){
            console.log(this.$route.query.testType)
            this.testType=JSON.parse(this.$route.query.testType)
        }
    }

}
</script>

<style scoped> 
el-table{
    margin-bottom: 200px;
}
</style>